---
version: 2.1
orbs:
  samvera: samvera/circleci-orb@1.0

jobs:
 test:
    parameters:
      ruby_version:
        type: string
      bundler_version:
        type: string
        default: 2.3.10

    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>

    environment:
      COVERAGE: true

    working_directory: ~/iiif_manifest

    steps:
      - samvera/cached_checkout
      - run:
          name: Check for a branch named 'master'
          command: |
            git fetch --all --quiet --prune --prune-tags
            if [[ -n "$(git branch --all --list master */master)" ]]; then
              echo "A branch named 'master' was found. Please remove it."
              echo "$(git branch --all --list master */master)"
            fi
            [[ -z "$(git branch --all --list master */master)" ]]
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: iiif_manifest
      - samvera/rubocop
      - samvera/parallel_rspec

workflows:
  version: 2
  ci:
    jobs:
      - test:
          name: "ruby3-2"
          ruby_version: "3.2.0"
      - test:
          name: "ruby3-1"
          ruby_version: "3.1.3"
      - test:
          name: "ruby3-0"
          ruby_version: "3.0.5"
      - test:
          name: "ruby2-7"
          ruby_version: "2.7.7"
      - test:
          name: "ruby2-6"
          ruby_version: "2.6.10"
      - test:
          name: "ruby2-5"
          ruby_version: "2.5.9"

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test:
          name: "ruby3-2"
          ruby_version: "3.2.0"
      - test:
          name: "ruby3-1"
          ruby_version: "3.1.3"
      - test:
          name: "ruby3-0"
          ruby_version: "3.0.5"
      - test:
          name: "ruby2-7"
          ruby_version: "2.7.7"
      - test:
          name: "ruby2-6"
          ruby_version: "2.6.10"
      - test:
          name: "ruby2-5"
          ruby_version: "2.5.9"
