---
version: 2.1
orbs:
  samvera: samvera/circleci-orb@1.0

jobs:
 test:
    parameters:
      ruby_version:
        type: string
      bundler_version:
        type: string
        default: 2.3.10

    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>

    environment:
      COVERAGE: true

    working_directory: ~/iiif_manifest

    steps:
      - samvera/cached_checkout
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: iiif_manifest
      - samvera/rubocop
      - samvera/parallel_rspec

workflows:
  version: 2
  ci:
    jobs:
      - test:
          name: "ruby3-0"
          ruby_version: "3.0.3"
      - test:
          name: "ruby2-7"
          ruby_version: "2.7.5"
      - test:
          name: "ruby2-6"
          ruby_version: "2.6.9"
      - test:
          name: "ruby2-5"
          ruby_version: "2.5.9"

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test:
          name: "ruby3-0"
          ruby_version: "3.0.3"
      - test:
          name: "ruby2-7"
          ruby_version: "2.7.5"
      - test:
          name: "ruby2-6"
          ruby_version: "2.6.9"
      - test:
          name: "ruby2-5"
          ruby_version: "2.5.9"
